CREATE TABLE IF NOT EXISTS teams (
    id serial PRIMARY KEY,
    name VARCHAR(256) UNIQUE UNIQUE NOT NULL,
    town VARCHAR(256) NOT NULL,
    created_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE IF NOT EXISTS matches (
    id serial PRIMARY KEY,
    home_team_fk INTEGER REFERENCES teams(id) NOT NULL,
    away_team_fk INTEGER REFERENCES teams(id) NOT NULL,
    fixture_dt TIMESTAMP,
    created_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO guest;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO guest;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO guest;