CREATE TABLE IF NOT EXISTS team (
    id serial PRIMARY KEY,
    name VARCHAR(256) UNIQUE UNIQUE NOT NULL,
    town VARCHAR(256) NOT NULL,
    website VARCHAR(256) NULL,
    createddttm TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE IF NOT EXISTS fixture (
    id serial PRIMARY KEY,
    hometeam_fk INTEGER REFERENCES team(id) NOT NULL,
    awayteam_fk INTEGER REFERENCES team(id) NOT NULL,
    fixturedttm TIMESTAMP,
    createddttm TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO guest;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO guest;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO guest;