services:
  app:
    build: .
    container_name: api
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8080:80
    volumes:
      - .:/app

  db:
    image: postgres
    container_name: pgsql-dev
    restart: always
    environment:
      POSTGRES_PASSWORD: guest
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

