services:
  app:
    build: .
    container_name: api
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8080:80
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: pgsql-dev
    restart: always
    environment:
      POSTGRES_PASSWORD: guest
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-dev
    restart: always
    ports:
      - 6379:6379

  nginx:
    image: nginx
    container_name: nginx-dev
    restart: always
    ports:
      - 8081:80

